//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSVHousing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPost
    {
        public int PostID { get; set; }
        public string Title { get; set; }
        public string Excerpt { get; set; }
        public string Content { get; set; }
        public string ImagePath { get; set; }
        public int UserID { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    
        public virtual User User { get; set; }
    }
}
