//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSVHousing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoommatePostComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoommatePostComment()
        {
            this.RoommatePostComments1 = new HashSet<RoommatePostComment>();
        }
    
        public int CommentID { get; set; }
        public string Content { get; set; }
        public int PostID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> ParentCommentID { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoommatePostComment> RoommatePostComments1 { get; set; }
        public virtual RoommatePostComment RoommatePostComment1 { get; set; }
        public virtual RoommatePost RoommatePost { get; set; }
        public virtual User User { get; set; }
    }
}
